# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassesDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nr_of_week', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=50)),
                ('stationary', models.BooleanField(default=True)),
                ('grade', models.CharField(choices=[('1', 'I-ST'), ('2', 'II-ST'), ('3', 'III-ST')], default='1', max_length=1)),
                ('year_of_study', models.SmallIntegerField()),
                ('sem_nr', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presence_type', models.CharField(choices=[('O', 'obecny'), ('N', 'nieobecny'), ('S', 'spóźniony'), ('U', 'usprawiedliwiony')], max_length=3)),
                ('classes_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ClassesDate')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=7)),
                ('sem_type', models.CharField(choices=[('l', 'letni'), ('z', 'zimowy')], default='z', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('subject', models.CharField(max_length=100)),
                ('classes_type', models.CharField(choices=[('WYK', 'Wykład'), ('CW', 'Ćwiczenia'), ('LAB', 'Laboratorium'), ('PR', 'Projekt'), ('SEM', 'Seminarium dyplomowe')], default='WYK', max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Group')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Group'),
        ),
        migrations.AddField(
            model_name='presence',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Student'),
        ),
        migrations.AddField(
            model_name='group',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Semester'),
        ),
        migrations.AddField(
            model_name='classesdate',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Classes'),
        ),
    ]
