# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='grade',
            field=models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III')], default='1', max_length=1),
        ),
    ]
