# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161004_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='place',
            field=models.CharField(default='P5-B', max_length=6),
            preserve_default=False,
        ),
    ]
