# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_group_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
