# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-22 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20161018_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='grade',
            field=models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V'), ('6', 'VI'), ('7', 'VII')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='group',
            name='sem_nr',
            field=models.CharField(choices=[('1', 'pierwszy'), ('2', 'drugi'), ('3', 'trzeci'), ('4', 'czwarty'), ('5', 'piąty'), ('6', 'szósty'), ('7', 'siódmy')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='group',
            name='year_of_study',
            field=models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV'), ('5', 'V'), ('6', 'VI'), ('7', 'VII')], default='1', max_length=1),
        ),
    ]
