# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-10 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20161022_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment', models.TextField()),
                ('classes_date', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.ClassesDate')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic', models.TextField()),
                ('classes_date', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.ClassesDate')),
            ],
        ),
    ]
