# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-12 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_comment_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classesdate',
            old_name='classes',
            new_name='group',
        ),
    ]
