# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-12 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170112_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='classes_date',
            new_name='classesdate',
        ),
        migrations.RenameField(
            model_name='presence',
            old_name='classes_date',
            new_name='classesdate',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='classes_date',
            new_name='classesdate',
        ),
    ]
