# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-20 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170113_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='presence_type',
            field=models.CharField(choices=[('O', 'obecny'), ('N', 'nieobecny'), ('S', 'spóźniony'), ('U', 'usprawiedliwiony'), ('N/A', 'zajęcia odwołane')], max_length=3),
        ),
    ]
