# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-28 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
